---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
    BASE_DIR: "/usr/percona-server"
  roles:
    - role: pro-tarballs
