---
# tasks file for tarball tests
  - name: Add epel-release
    yum:
      state: present
      name: epel-release
    when: ansible_os_family == "RedHat"

  - name: install needed packages for running tests with apt
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - git
      - unzip
      - wget
      - python3
      - python3-pip
      - libaio1 
      - libnuma1
      - tar
      - gawk
    register: result
    until: result is not failed
    when: ansible_os_family == "Debian"

  - name: install needed packages for running tests with yum
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - git
      - unzip
      - wget
      - libaio
      - numactl
      - tar
      - gawk
      - python3
      - python3-pip
      - libtirpc
      - openldap
    when: ansible_os_family == "RedHat"

  - name: assign minimal value
    set_fact:
      MINIMAL:  "{{ '-minimal' if lookup('env', 'BUILD_TYPE_MINIMAL') == 'true' else '' }}"

  - name: get GLIBC_VERSION
    set_fact:
      GLIBC_VERSION: "{{ '2.35' if ansible_os_family == 'Debian' else '2.34' }}"

  - name: get TARBALL_NAME
    set_fact:
      TARBALL_NAME: "Percona-Server-Pro-{{ lookup('env', 'PS_VERSION') }}-Linux.x86_64.glibc{{ GLIBC_VERSION }}{{ MINIMAL }}.tar.gz"

  # - name: get main repo TARBALL_LINK
  #   set_fact:
  #     TARBALL_LINK: "https://repo.percona.com/private/{{ lookup('env', 'USERNAME') }}-{{ lookup('env', 'PASSWORD') }}/ps-80-pro/tarballs/Percona-Server-{{ lookup('env', 'PS_VERSION') }}/"

  - name: get testing repo TARBALL_LINK
    set_fact:
      TARBALL_LINK: "https://repo.percona.com/private/{{ lookup('env', 'USERNAME') }}-{{ lookup('env', 'PASSWORD') }}/qa-test/ps-gated-{{ lookup('env', 'PS_VERSION') }}/{{ TARBALL_NAME }}"

  - name: download package-testing repo branch with wget
    command: "{{ item }}"
    with_items:
    - rm -rf package-testing
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip https://github.com/eleo007/package-testing/archive/pro_build_job.zip
    - unzip master.zip
    - rm -f master.zip
    - mv package-testing-pro_build_job package-testing

  - name: Download {{ TARBALL_NAME }}
    get_url:
      url: '{{ TARBALL_LINK }}'
      dest: /tmp/percona-server-{{ lookup('env', 'PS_VERSION') }}.tar.gz
      mode: '0644'

  - name: Unpack new tarball
    unarchive:
      src: /tmp/percona-server-{{ lookup('env', 'PS_VERSION') }}.tar.gz
      dest: /
      remote_src: yes
      extra_opts:
      - --transform
      - 's,^/*[^/]*,/usr/percona-server,S'
