---
# tasks file for tarball tests
  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
    when: ansible_os_family == "Debian"

  - name: install needed packages for running tests with apt
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - git
      - wget
      - python3.6 
      - sudo python3 get-pip.py
      - libaio1 
      - libnuma1
    retries: 60
    delay: 10
    register: result
    until: result is not failed
    when: ansible_os_family == "Debian"

  - name: install needed packages for running tests with yum
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - git
      - unzip
      - wget
      - libaio
      - numactl
      - openssl
      - tar
      - perl-Data-Dumper
      - epel-release
      - python3
      - python3-pip
      - libtirpc
      - openldap
    when: ansible_os_family == "RedHat"

  - name: assign minimal value
    set_fact:
      MINIMAL:  "{{ '-minimal' if lookup('env', 'BUILD_TYPE_MINIMAL') == True else '' }}"

  - name: get GLIBC_VERSION
    set_fact:
      GLIBC_VERSION: "{{ '2.35' if ansible_os_family == 'Debian' else '2.34' }}"
  
  - name: get TARBALL_DIR_NAME
    set_fact:
      TARBALL_DIR_NAME: "Percona-Server-Pro-{{ lookup('env', 'PS_VERSION') }}-Linux.x86_64.glibc{{ GLIBC_VERSION }}{{ MINIMAL }}"

  - name: get TARBALL_NAME
    set_fact:
      TARBALL_NAME: "{{ TARBALL_DIR_NAME }}.tar.gz"

  # - name: get main repo TARBALL_LINK
  #   set_fact:
  #     TARBALL_LINK: "https://repo.percona.com/private/{{ lookup('env', 'USERNAME') }}-{{ lookup('env', 'PASSWORD') }}/ps-80-pro/tarballs/Percona-Server-{{ lookup('env', 'PS_VERSION') }}/"


  - name: get main repo TARBALL_LINK
    set_fact:
      TARBALL_LINK: "https://repo.percona.com/private/{{ lookup('env', 'USERNAME') }}-{{ lookup('env', 'PASSWORD') }}/qa-test/ps-gated-{{ lookup('env', 'PS_VERSION') }}/{{ TARBALL_NAME }}"

  - name: download package-testing repo branch with wget
    command: "{{ item }}"
    with_items:
    - rm -rf package-testing
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip https://github.com/eleo007/package-testing/archive/pro_build_job.zip
    - unzip master.zip
    - rm -f master.zip
    - mv package-testing-pro_build_job package-testing

  - name: Download tarball for ol9 from url
    get_url:
      url: '{{ TARBALL_LINK }}'
      dest: /tmp/percona-server-{{ lookup('env', 'PS_VERSION') }}.tar.gz
      mode: '0644'

  - name: Unpack new tarball
    unarchive:
      src: /tmp/percona-server-{{ lookup('env', 'PS_VERSION') }}.tar.gz
      dest: /
      remote_src: yes
      mode: '0777'
     extra_opts:
     - --transform
     - 's,^/*[^/]*,/usr/percona-server,S'


  - name: Rename tarball DIR
    command: mv /{{ TARBALL_DIR_NAME }} /percona-server-{{ lookup('env', 'PS_VERSION') }}

  - name: Pause for 1 minutes
    pause:
      minutes: 1

  # - name: Unpack tarball
  #   command: "{{ item }}"
  #   with_items:
  #   - mkdir 
  #   - wget {{ TARBALL_LINK }} -o {{ playbook_dir }}
  #   - tar -zxf {{ TARBALL_NAME }} -C {{ playbook_dir }}/ps-binary-tarball
