---
# tasks file for pdpxc
- name: include playbook for removing Percona repo
  include: ../../../tasks/remove_percona_repository.yml

- name: Install percona release
  include: ../../tasks/install_percona_release.yml

- name: enable the PDMYSQL-80 repo
  command: percona-release enable-only pdpxc-{{ version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'REPO') }}"
    version: "{{ lookup('env', 'VERSION') }}"

- name: clean and update yum cache
  shell: |
    yum clean all
    yum makecache
  when: ansible_os_family == "RedHat"

- name: disable the mysql module on RHEL/CentOS 8
  command: yum module disable mysql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

- name: disable the mariadb module on RHEL/CentOS 8
  command: yum module disable mariadb -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

- name: install PXC 8 deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    # - percona-xtradb-cluster-full
    # - percona-xtradb-cluster-client
    # - percona-xtradb-cluster-common
    # - percona-xtradb-cluster-dbg
    # - percona-xtradb-cluster-garbd-debug
    # - percona-xtradb-cluster-garbd
    # - percona-xtradb-cluster-server
    # - percona-xtradb-cluster-server-debug
    # - percona-xtradb-cluster-test
    - percona-xtradb-cluster
  when: ansible_os_family == "Debian"

- name: install HA Proxy 8 deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - percona-haproxy
    - percona-haproxy-doc
    - percona-vim-haproxy
  when: ansible_os_family == "Debian"

- name: install xinetd 8 deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - xinetd
  when: ansible_os_family == "Debian"

- name: bootstrap pxc node
  service: name=mysql@bootstrap.service state=started
  when: ansible_os_family == "Debian"

- name: Update haproxy config
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen mysql-cluster
          bind :9201
          mode tcp
          balance roundrobin
          option  httpchk
          server db01 localhost:3306 check port 9200 inter 12000 rise 3 fall 3

- name: Create mysqlchk cnf
  copy:
    src: mysqlchk
    dest: /etc/xinetd.d/mysqlchk
    owner: root
    group: root
    mode: 0644

- name: set mysqlchk port to 9200
  lineinfile:
    path: /etc/services
    line: mysqlchk        9200/tcp                # mysqlchk
