  - name: Install MySQL apt repository package
    apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
    when: ansible_os_family == "Debian"

  - name: replace the default MySQL 8.0 repo with 5.7
    replace:
      path: /etc/apt/sources.list.d/mysql.list
      regexp: 'mysql-8.0'
      replace: 'mysql-5.7'
      backup: yes
    when: ansible_os_family == "Debian"

  - name: Install MySQL RHEL 6 yum repository package
    yum: name=https://dev.mysql.com/get/mysql80-community-release-el6-2.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: Install MySQL RHEL 7 yum repository package
    yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"