  - name: install PXC 5.7 new deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-xtradb-cluster-full-57
      - percona-xtradb-cluster-57
      - percona-xtradb-cluster-source-5.7
    when: ansible_os_family == "Debian"

  - name: install PXC 5.7 new rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - Percona-XtraDB-Cluster-full-57
      - Percona-XtraDB-Cluster-57
    when: ansible_os_family == "RedHat"