# Installs Percona Release Tool
#
- name: Install percona-release package Debian
  when: ansible_os_family == "Debian"
  apt:
    #deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    force: true

- name: Install percona-release package RedHat
  when: ansible_os_family == "RedHat"
  command: yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  #command: yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
#  args:
#    warn: no

- name: clean and update yum cache
  when: ansible_os_family == "RedHat"
  shell: |
    yum clean all
  #   yum makecache
