# Enable psmdb repo and install psmdb
  - name: include tasks for enabling psmdb 44 repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-44 release"

  - name: include tasks for installing psmdb 44 packages
    include_tasks: ../tasks/install_psmdb.yml
    vars:
      packages: percona-server-mongodb

# Start psmdb service
  - name: start mongod service
    service: 
      name: mongod
      state: started
