---
# tasks file for pdps
  - name: include playbook for removing Percona repo
    include: ../../../tasks/remove_percona_repository.yml

  - name: Install percona release
    include: ../../tasks/install_percona_release.yml

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"

  - name: disable the mysql module on RHEL/CentOS 8
    command: yum module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: disable the mariadb module on RHEL/CentOS 8
    command: yum module disable mariadb -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - set_fact:
      major_repo: "{{ lookup('env', 'MAJOR_REPO') }}"

  - name: enable the pdps-{{ version }} repo
    command: percona-release enable-only pdps-{{ version }} {{ repo }}
    vars:
      repo: "{{ lookup('env', 'REPO') }}"
      version: "{{ lookup('env', 'VERSION') }}"
    when: not major_repo

  - name: enable the major pdps-{{ version }} repo
    command: percona-release enable-only pdps-{{ version }} {{ repo }}
    vars:
      repo: "{{ lookup('env', 'REPO') }}"
      version: "{{ lookup('env', 'VERSION').split('.')[0] + '.' + lookup('env', 'VERSION').split('.')[1] }}"
    when: major_repo

  - name: install Percona Toolkit
    command: percona-release show
    register: repolist

  - name: show list of enabled repos
    debug:
      var: repolist
