  - name: enable the mongo repo pdmdb-6.0
    command: percona-release enable pdmdb-6.0

  - name: install Mongo deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "Debian" and ansible_distribution_release != "bookworm"

  - name: install Mongo rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "RedHat"