---

  - name: disable all percona-release repos
    command: percona-release disable all

  - name: enable percona-release tools experimental
    command: percona-release enable tools experimental

  - name: purge percona-server packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: absent
      purge: true
    vars:
      packages:
      - percona-server*
    when: ansible_os_family == "Debian"

  - name: remove Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
      disablerepo: "epel"
    vars:
      packages:
      - percona-server*
    when: ansible_os_family == "RedHat"

  - name: install Telemetry Agent deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-telemetry-agent
    when: ansible_os_family == "Debian"

  - name: install Telemetry Agent rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-telemetry-agent
    when: ansible_os_family == "RedHat"

  - name: enable the mongo repo pdmdb-6.0
    command: percona-release enable pdmdb-6.0

  - name: install Mongo deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "Debian"

  - name: install Mongo rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "RedHat"