---
# tasks file for pdpxc

- name: include playbook for removing Percona repo
  include: ../../../tasks/remove_percona_repository.yml

- name: download package-testing repo with wget
  command: "{{ item }}"
  with_items:
  - rm -rf /package-testing
  - rm -f master.zip
  - wget --no-check-certificate -O master.zip "https://github.com/eleo007/package-testing/archive/{{ branch }}.zip"
  - unzip master.zip
  - rm -f master.zip
  - mv "package-testing-{{ branch }}" /package-testing
  vars:
    branch: "{{ lookup('env', 'TESTING_BRANCH') }}"