---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of PS 8.0, PT and PXB 8.0
#   does some tests

# Cosmic is still missing python
# import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    install_mysql_shell: "{{ lookup('env', 'install_mysql_shell', default='') }}"
  environment:
    install_mysql_shell: '{{ install_mysql_shell }}'
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
    # PERCONA_TELEMETRY_CHECK_INTERVAL: 10

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

#   - name: Copy telemetry agent binary
#     ansible.builtin.copy:
#       src: /home/eleonora.zinchenko/telemetry-agent/bin/telemetry-agent
#       dest: telemetry-agent
#       mode: '777'

  - name: enforce SELinux on CentOS
    selinux:
      policy: targeted
      state: enforcing
    when: ansible_os_family == "RedHat"

  - name: get selinux status
    command: sestatus
    register: selinux_status
    when: ansible_os_family == "RedHat"

  - name: list selinux status
    debug:
      var: selinux_status
    when: ansible_os_family == "RedHat"

#   - name: download and extract world database
#     command: "{{ item }}"
#     with_items:
#     - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

# # Disable Percona Toolkit installation till its supported in OL9 and Jammy
# #  - name: install Percona Toolkit new deb packages
# #    include_tasks: ../tasks/install_pt.yml
#   - name: include playbook for removing Percona repo
#     include_tasks: ../tasks/remove_percona_repository.yml

  - name: Install percona release
    include_tasks: ../tasks/install_percona-release.yml

  - name: enable percona-release tools experimental
    command: percona-release enable tools experimental

#   - name: Update cache
#     command: apt update
#     when: ansible_os_family == "Debian"

  - name: install Telemetry Agent deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-telemetry-agent
    when: ansible_os_family == "Debian"

  - name: install Telemetry Agent rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-telemetry-agent
    when: ansible_os_family == "RedHat"

  - name: disable percona-release tools experimental
    command: percona-release disable tools experimental

  - name: enable the proxysql repo
    command: percona-release enable proxysql

  - name: install Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - proxysql2
    when: ansible_os_family == "Debian"

  - name: install Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - proxysql2
    when: ansible_os_family == "RedHat"

  - name: enable the pdps-8x-innovation testing 
    command: percona-release enable pdps-8x-innovation testing

  - name: install Percona Server and backup deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-source
      - percona-server-client
      - percona-server-rocksdb
      - percona-mysql-router
      - percona-xtrabackup-80
      - percona-toolkit
    when: ansible_os_family == "Debian"

  - name: install Percona Server and backup rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-client
      - percona-server-rocksdb
      - percona-mysql-router
      - percona-xtrabackup-80
      - percona-toolkit
    when: ansible_os_family == "RedHat"


  - name: enable the pdps-8.0.36
    command: percona-release enable pdps-8.0.36

  - name: install Orchestrator deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-orchestrator-cli
      - percona-orchestrator-client
      - percona-orchestrator
    when: ansible_os_family == "Debian"

  - name: install Orchestrator rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-orchestrator-cli
      - percona-orchestrator-client
      - percona-orchestrator
    when: ansible_os_family == "RedHat"


  - name: enable the pdpxc-8.0.35 testing
    command: percona-release enable pdpxc-8.0.35 testing

  - name: install percona-haproxy rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-haproxy
    when: ansible_os_family == "RedHat"

  - name: install percona-haproxy deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-haproxy
    when: ansible_os_family == "Debian"

  - name: enable the original repo
    command: percona-release enable original

  - name: install PMM client rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - pmm2-client
    when: ansible_os_family == "RedHat"

  - name: install PMM client deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - pmm2-client
    when: ansible_os_family == "Debian"

  - name: enable the mongo repo pdmdb-7.0 experimental
    command: percona-release enable pdmdb-7.0 experimental

  - name: install Mongo deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "Debian"

  - name: install Mongo rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - percona-server-mongodb-mongos
    when: ansible_os_family == "RedHat"


  # - name: enable the ppg repo ppg-16
  #   command: percona-release enable ppg-16
  #   when: ansible_os_family == "Debian"

  # - name: setup the ppg repo ppg-16 for rhel
  #   command: percona-release setup -y ppg-16
  #   when: ansible_os_family == "RedHat"

  # - name: install PPG deb packages
  #   apt:
  #     name: "{{ packages }}"
  #     update_cache: yes
  #     state: latest
  #   vars:
  #     packages:
  #     - percona-ppg-server-16
  #     - percona-pgbouncer
  #     - percona-patroni
  #     - percona-postgresql-16-pgaudit
  #     - percona-pgaudit16-set-user
  #     - percona-pgbadger
  #     - percona-pgbouncer
  #     - percona-pg-gather
  #     - percona-pgpool2
  #     - percona-postgresql-*-repack
  #     - percona-pg-stat-monitor*
  #     - percona-postgis
  #     - percona-postgresql-*-wal2json
  #     - percona-pgbackrest
  #     - etcd
  #   when: ansible_os_family == "Debian"

  # - name: install PPG rpm packages
  #   yum:
  #     name: "{{ packages }}"
  #     state: latest
  #     update_cache: yes
  #   vars:
  #     packages:
  #     - percona-ppg-server16
  #     - percona-pgbouncer
  #     - percona-pgaudit*_set_user
  #     - percona-pgbadger
  #     - percona-pg_gather
  #     - percona-patroni
  #     - percona-pgpool-II*
  #     # - percona-postgis*
  #     - etcd
  #   when: ansible_os_family == "RedHat"

  # - name: make changes for pgpool2
  #   command: sudo dnf config-manager --set-enabled codeready-builder-for-rhel-9-x86_64-rpms
  #   when: ansible_os_family == "RedHat"

  # - name: install PPG rpm packages
  #   yum:
  #     name: "{{ packages }}"
  #     state: latest
  #     update_cache: yes
  #   vars:
  #     packages:
  #      - percona-pgpool-II
  #   when: ansible_os_family == "RedHat"


  - name: make changes for postgis
    command: "{{ item }}" 
    with_items:
      - yum install epel-release
      - dnf module enable -y llvm-toolset
      - dnf config-manager --set-enabled ol8_codeready_builder
    when: ansible_os_family == "RedHat"

  - name: install PPG rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgis33
    when: ansible_os_family == "RedHat"

  # - name: Update PERCONA_TELEMETRY_CHECK_INTERVAL default
  #   ansible.builtin.lineinfile:
  #     path: /etc/default/percona-telemetry-agent
  #     regex: 'PERCONA_TELEMETRY_CHECK_INTERVAL=86400'
  #     line: PERCONA_TELEMETRY_CHECK_INTERVAL=10
  #   when: ansible_os_family == "Debian"

  # - name: Update PERCONA_TELEMETRY_URL default
  #   ansible.builtin.lineinfile:
  #     path: /etc/default/percona-telemetry-agent
  #     regex: 'PERCONA_TELEMETRY_URL=https://check.percona.com/v1/telemetry/GenericReport'
  #     line: PERCONA_TELEMETRY_URL=https://check-dev.percona.com/v1/telemetry/GenericReport
  #   when: ansible_os_family == "Debian"


  # - name: Update PERCONA_TELEMETRY_CHECK_INTERVAL default
  #   ansible.builtin.lineinfile:
  #     path: /etc/sysconfig/percona-telemetry-agent
  #     regex: 'PERCONA_TELEMETRY_CHECK_INTERVAL=86400'
  #     line: PERCONA_TELEMETRY_CHECK_INTERVAL=10
  #   when: ansible_os_family == "RedHat"

  # - name: Update PERCONA_TELEMETRY_URL default
  #   ansible.builtin.lineinfile:
  #     path: /etc/sysconfig/percona-telemetry-agent
  #     regex: 'PERCONA_TELEMETRY_URL=https://check.percona.com/v1/telemetry/GenericReport'
  #     line: PERCONA_TELEMETRY_URL=https://check-dev.percona.com/v1/telemetry/GenericReport
  #   when: ansible_os_family == "RedHat"

  # - name: install haproxy packages
  #   apt:
  #     name: "{{ packages }}"
  #     update_cache: yes
  #     state: latest
  #   vars:
  #     packages:
  #     - haproxy
  #   when: ansible_os_family == "Debian"

  # - name: install haproxy packages
  #   yum:
  #     name: "{{ packages }}"
  #     state: latest
  #     update_cache: yes
  #     skip_broken: yes
  #   vars:
  #     packages:
  #     - haproxy
  #     # - percona-postgis*
  #     - etcd
  #   when: ansible_os_family == "RedHat"

  # - name: ensures /usr/local/percona/telemetry/ps dir exists
  #   file: 
  #     path: "/usr/local/percona/telemetry/ps"
  #     state: directory

  # - name: Create test file
  #   copy:
  #     content: |
  #               {
  #               "ansible_test_string":"ansible_test_string"
  #               }
  #     dest: "/usr/local/percona/telemetry/ps/{{ ansible_date_time.epoch }}-test_content.json"
################################333

  # - name: install PPG deb packages
  #   apt:
  #     name: "{{ packages }}"
  #     update_cache: yes
  #     state: latest
  #   vars:
  #     packages:
  #     - postgresql-16
  #     - patroni + 
  #     - postgresql-16-pgaudit
  #     - pgbadger + 
  #     - pgbouncer +
  #     - postgresql-16-pgpool2
  #     - postgresql-16-repack
  #     - postgis + ? 
  #     - postgresql-16-wal2json
  #     - pgbackrest +
  #   when: ansible_os_family == "Debian"

  # - name: install PPG rpm packages
  #   yum:
  #     name: "{{ packages }}"
  #     state: latest
  #     update_cache: yes
  #     skip_broken: yes
  #   vars:
  #     packages:
  #     - patroni +
  #     - pgaudit_16 +
  #     - pgbackrest +
  #     - pgbouncer + 
  #     - pg_repack_16 + 
  #     - pgbadger + 
  #     - pgpool-II +
  #     - postgis34_16 - 
  #     - wal2json_16 - 
  #     # - percona-postgis*
  #     - etcd
  #   when: ansible_os_family == "RedHat"