---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of Percona-Toolkit
#   does some tests
#- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
#      client: "{{ lookup('env', 'install_repo') }}"
      client: "{{ lookup('env', 'client_to_test') }}"
#      repo_name: "{{ lookup('env', 'repo_name') }}"
      install_repo: "{{ lookup('env', 'install_repo') }}"

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks to install pt from [pt,tools, original] repos
    include_tasks: ../tasks/enable_pt_repos_and_install.yml
    vars:
      - repo_name: "{{ item }}"
    loop:
      - tools
      - pt
      - original
