---
# This playbook does following:
#   enables Percona testing repository
#   updates Percona-Toolkit to the latest version
#   does some tests

- hosts: all
  become: true
  become_method: sudo
  vars:
      client: "{{ lookup('env', 'install_repo') }}"

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling main repo
    include: ../tasks/enable_tools_main_repo.yml

  - name: check enabled repos
    command: percona-release show
    register: repo_list

  - name: output repos list
    debug:
      var: repo_list

  - name: include tasks for pt installation
    include_tasks: ../tasks/install_pt.yml

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Check whether a package called percona-toolkit is installed
    ansible.builtin.debug:
      msg: "{{ ansible_facts.packages['percona-toolkit'] }} versions of percona-toolkit is installed!"
    when: "'percona-toolkit' in ansible_facts.packages"

# remove till the PT-1959 is fixed
#  - name: check that pt version is correct
#    command: /package-testing/version_check.sh pt
#
#  - name: start proxysql service
#    service: name=proxysql state=started
#
#  - name: stop proxysql service
#    service: name=proxysql state=stopped
#
#  - name: start proxysql service
#    service: name=proxysql state=started
#
#  - name: run client_check tasks
#    include_tasks: ../tasks/client_check.yml

  - name: include tasks for enabling test repo
    include_tasks: ../tasks/enable_tools_testing_repo.yml

  - name: check enabled repos
    command: percona-release show
    register: repo_list

  - name: output repos list
    debug:
      var: repo_list

  - name: remove pt packages
    include: ../tasks/remove_pt.yml

#  - name: check if process is stopped after package removal
#    command: /package-testing/check_running.sh proxysql stopped
