---
# This playbook does following:
#   enables Percona testing repository
#   updates Percona-Toolkit to the latest version
#   does some tests

- hosts: all
  become: true
  become_method: sudo
  vars:
      client: "{{ lookup('env', 'install_repo') }}"
      repo_name: "{{ lookup('env', 'repo_name') }}"

  tasks:
  - name: Get additional info
    debug:
      var: ansible_facts.distribution_release

  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_only_main_repo_for_pt.yml

  - name: check enabled repos
    command: percona-release show
    register: repo_list

  - name: output repos list
    debug:
      var: repo_list

  - name: include tasks for pt installation
    include_tasks: ../tasks/install_pt.yml

# remove till the PT-1959 is fixed
#  - name: check that pt version is correct
#    command: /package-testing/version_check.sh pt
#
#  - name: start proxysql service
#    service: name=proxysql state=started
#
#  - name: stop proxysql service
#    service: name=proxysql state=stopped
#
#  - name: start proxysql service
#    service: name=proxysql state=started
#
#  - name: run client_check tasks
#    include_tasks: ../tasks/client_check.yml

  - name: include tasks for enabling testing repo
    include_tasks: ../tasks/enable_only_testing_repo_for_pt.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: include tasks for enabling experimental repo
    include_tasks: ../tasks/enable_only_experimental_repo_for_pt.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: include tasks for pt installation
    include_tasks: ../tasks/install_pt.yml

  - name: check enabled repos
    command: percona-release show
    register: repo_list

  - name: output repos list
    debug:
      var: repo_list

  - name: remove pt packages
    include: ../tasks/remove_pt.yml

#  - name: check if process is stopped after package removal
#    command: /package-testing/check_running.sh proxysql stopped
