---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of Percona-Toolkit
#   installs latest version of PS-57, PS-80; MysqL-57, MySQL-80

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling ps57 main repo
    include_tasks: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_with') == "ps57"

  - name: include tasks for installing ps57 packages
    include_tasks: ../tasks/install_ps57.yml
    when: lookup('env', 'install_with') == "ps57"

  - name: include tasks for enabling ps80 main repo
    include_tasks: ../tasks/enable_ps8_main_repo.yml
    when: lookup('env', 'install_with') == "ps80"

  - name: include tasks for installing ps80 packages
    include_tasks: ../tasks/install_ps80.yml
    when: lookup('env', 'install_with') == "ps80"

  - name: include tasks for enabling pxc 57 repo
    include_tasks: ../tasks/enable_pxc57_main_repo.yml
    when: lookup('env', 'install_with') == "pxc57"

  - name: include tasks for installing pxc 57 packages
    include_tasks: ../tasks/install_pxc57.yml
    when: lookup('env', 'install_with') == "pxc57"

  - name: include tasks for enabling pxc 80 repo
    include_tasks: ../tasks/enable_pxc80_main_repo.yml
    when: lookup('env', 'install_with') == "pxc80"

  - name: include tasks for installing pxc 80 packages
    include_tasks: ../tasks/install_pxc80.yml
    when: lookup('env', 'install_with') == "pxc80"

  - name: include tasks for enabling upstream 57 repo
    include_tasks: ../tasks/enable_upstream57_repo.yml
    when: lookup('env', 'install_with') == "upstream57"

  - name: include tasks for installing upstream 57 packages
    include_tasks: ../tasks/install_upstream57.yml
    when: lookup('env', 'install_with') == "upstream57"

  - name: include tasks for enabling upstream 80 repo
    include_tasks: ../tasks/enable_upstream80_repo.yml
    when: lookup('env', 'install_with') == "upstream80"

  - name: include tasks for installing upstream 80 packages
    include_tasks: ../tasks/install_upstream80.yml
    when: lookup('env', 'install_with') == "upstream80"

  - name: include tasks for enabling tools test repo
    include_tasks: ../tasks/enable_only_tools_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling tools main repo
    include_tasks: ../tasks/enable_only_tools_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling tools experimental repo
    include_tasks: ../tasks/enable_only_tools_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: check enabled repos
    command: percona-release show
    register: repo_list

  - name: output repos list
    debug:
      var: repo_list.stdout_lines

  - name: include tasks for pt installation
    include_tasks: ../tasks/install_pt.yml

  - name: list installed percona packages
    shell: apt list --installed|egrep -i "percona|mysql"
    register: packages_list
    when: ansible_os_family == "Debian"

  - name: output percona installed packages list
    debug:
      var: packages_list.stdout_lines
    when: ansible_os_family == "Debian"

  - name: list installed percona packages
    shell: yum list installed|egrep -i "percona|mysql"
    register: packages_list
    when: ansible_os_family == "RedHat"

  - name: output percona installed packages list
    debug:
      var: packages_list.stdout_lines
    when: ansible_os_family == "RedHat"

# remove till the PT-1959 is fixed
#  - name: check that pt version is correct
#    command: /package-testing/version_check.sh pt

  - name: remove pt packages
    include: ../tasks/remove_pt.yml
